#ifndef GAME_PARAM_H
#define GAME_PARAM_H

#define SCREEN_WIDTH 1024
#define SCREEN_HEIGHT 700

#define MENU_WIDTH 500
#define MENU_HEIGHT 700

#define PLAYER_SPEED 50.0f

#define ELEMENT_SIZE 20.0f

#define ENTITIES_NUMBER 15

#define GHOST_TIME 2

#endif //GAME_PARAM_H